#!/bin/bash

## Copyright (C) 2020 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://forums.whonix.org/t/one-time-popup-notification-of-whonix-15-deprecation-once-whonix-16-was-released/11720
## https://forums.whonix.org/t/do-not-show-this-message-again-generic-one-time-popup/8066

#set -x
set -e

## sets: PROJECT_NAME
## sets: PROJECT_HOMEPAGE
## sets: derivative_major_release_version
source /usr/libexec/helper-scripts/origins-parser

status_file=~/.config/legacy-dist/deprecation-notice/dismissed-version-17

#true "INFO: This version is not yet deprecated."
#exit 0

#if test -e /usr/share/qubes/marker-vm ; then
   ## https://forums.whonix.org/t/current-status-qubes-4-1-whonix-16/17191
   #true "INFO: Skip in Qubes."
   #exit 0
#fi

if [ "$derivative_major_release_version" = "" ]; then
   echo "ERROR: version file does not exist or is empty!"
   exit 1
fi

if [ "$derivative_major_release_version" -ge "17" ]; then
   true "INFO: Not yet deprecated, ok."
   exit 0
fi

if test -e /usr/share/qubes/marker-vm; then
   true "INFO: Not yet deprecated, ok.

Kicksecure 17 and Whonix 17 will remain supported until 1 month after Qubes R4.3 stable has been released.

See also:
decide availability of Kicksecure, and Whonix 18 (Debian trixie based) on Qubes R4.2 versus R4.3 #10219
https://github.com/QubesOS/qubes-issues/issues/10219"
   exit 0
fi

title="DEPRECATION NOTICE"

text="<p>Support Status of this Major Version: <b>Deprecated!</b>
<br />
<br />Major release version <u><code>$derivative_major_release_version</code></u> has been deprecated.
<br />
<br />No more security support will be provided.
<br />
<br /><b>A Release Upgrade is strongly recommended!</u></b>
<br />
<br />${PROJECT_HOMEPAGE}/wiki/Stay_Tuned
<br />${PROJECT_HOMEPAGE}/wiki/Release_Upgrade
</p>"

/usr/libexec/msgcollector/one-time-popup "$status_file" "$title" "$text"
