#!/bin/bash

get_build_version() {
   ## fallback
   whonix_build_version="Could not read Whonix Build Version File. (Code: 3) Please report this bug!"

   local build_version_file
   if [ -f "/usr/share/whonix/build_version" ]; then
      build_version_file="/usr/share/whonix/build_version"
   elif [ -f "/var/lib/anon-dist/build_version" ]; then
      build_version_file="/var/lib/anon-dist/build_version"
   fi

   if [ "$build_version_file" = "" ]; then
      whonix_build_version="There is no Whonix Build Version File. (Code: 4) Please report this bug!"
   else
      if [ -f "$build_version_file" ]; then
         whonix_build_version="$(cat "$build_version_file")"
      fi
   fi

   ## fallback
   if [ "$whonix_build_version" = "" ]; then
      whonix_build_version="Could not read Whonix Build Version File. (Code: 5) Please report this bug!"
   fi
}

tb_folder_migration_whonix_eleven_to_twelve() {
   ## We need to move Tor Browser from the old location(s) to the new ones.
   ## Otherwise existing users who upgrade would be notified "Tor Browser not
   ## installed" and asked "want to install Tor Browser?".

   if [ -d /home/user/.tb/tor-browser ]; then
      echo "$0 $FUNCNAME INFO: New folder /home/user/.tb/tor-browser already exists. Skipping."
      return 0
   fi

   if pgrep firefox ; then
      echo "$0 $FUNCNAME INFO: Tor Browser likely already running. Not trying to migrate to new location." >&2
      return 1
   fi

   if [ -f "/var/lib/whonix/do_once/tb_folder_migration_whonix_eleven_to_twelve" ]; then
      true "/var/lib/whonix/do_once/tb_folder_migration_whonix_eleven_to_twelve exists. Already done."
      return 0
   fi

   mkdir --parents "/var/lib/whonix/do_once"

   local folder_name

   for folder_name in /home/user/tor-browser_* /home/user/.tb/tor-browser_* ; do
      if echo "$folder_name" | grep -q '.old.' ; then
         continue
      fi
      if [ ! -d "$folder_name" ]; then
         continue
      fi

      sudo --non-interactive -u user mv "$folder_name" /home/user/.tb/tor-browser || \
         { echo "$0 $FUNCNAME ERROR: Moving from '$folder_name' to '/home/user/.tb/tor-browser' failed." >&2 && break; };

      echo "$0 $FUNCNAME INFO: Moved '$folder_name' to '/home/user/.tb/tor-browser'."

      break
   done

   touch "/var/lib/whonix/do_once/tb_folder_migration_whonix_eleven_to_twelve"
}

timesync_apparmor_profile_delete() {
   if [ -f "/var/lib/whonix/do_once/timesync_apparmor_profile_delete" ]; then
      true "/var/lib/whonix/do_once/timesync_apparmor_profile_delete exists. Already done."
      return 0
   fi
   mkdir --parents "/var/lib/whonix/do_once"

   rm -f "/etc/apparmor.d/usr.bin.timesync"

   touch "/var/lib/whonix/do_once/timesync_apparmor_profile_delete"
}

whonix_repository_rerun() {
   if [ -f "/var/lib/whonix/do_once/whonix_repository_rerun" ]; then
      true "/var/lib/whonix/do_once/whonix_repository_rerun exists. Already done."
      return 0
   fi
   mkdir --parents "/var/lib/whonix/do_once"

   if test -x "/var/lib/dpkg/info/whonix-repository.postinst" ; then
      ## gpg and /etc/apt/trusted.gpg to gpg2 and /etc/apt/trusted.gpg.d/whonix.gpg
      ## migration will fail due to uwt not supporting gpg2 and due to whonix-repository
      ## being upgraded earlier than uwt. Also uwt should not be a dependency of
      ## whonix-repository.
      DEBDEBUG=1 DPKG_MAINTSCRIPT_PACKAGE=whonix-repository DPKG_MAINTSCRIPT_NAME=postinst /var/lib/dpkg/info/whonix-repository.postinst configure || true
   fi

   touch "/var/lib/whonix/do_once/whonix_repository_rerun"
}

command_not_found_sources_list_fix() {
   if [ -f "/var/lib/whonix/do_once/${FUNCNAME}_version_1" ]; then
      return 0
   fi

   if [ ! -e /etc/apt/sources.list ]; then
      ## https://forums.whonix.org/t/command-not-found-warningcould-not-open-file-etc-apt-sources-list/7903
      touch /etc/apt/sources.list || true
   fi

   mkdir --parents "/var/lib/whonix/do_once"
   touch "/var/lib/whonix/do_once/${FUNCNAME}_version_1"
}

command_not_found_permission_fix() {
   if [ -f "/var/lib/whonix/do_once/${FUNCNAME}_version_1" ]; then
      return 0
   fi

   if [ -f /var/lib/command-not-found/commands.db ]; then
      ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917455
      chmod o+r /var/lib/command-not-found/commands.db || true
   fi

   mkdir --parents "/var/lib/whonix/do_once"
   touch "/var/lib/whonix/do_once/${FUNCNAME}_version_1"
}

if [ "$(id -u)" != "0" ]; then
   echo "$0 ERROR: must run as root!" >&2
   exit 1
fi

## Fix for:
## dpkg-maintscript-helper: error: couldn't identify the package
[ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] || DPKG_MAINTSCRIPT_PACKAGE="whonix-legacy"
[ -n "$DPKG_MAINTSCRIPT_NAME" ] || DPKG_MAINTSCRIPT_NAME="preinst"
export DPKG_MAINTSCRIPT_PACKAGE DPKG_MAINTSCRIPT_NAME
timeout --kill-after 60 60 /var/lib/dpkg/info/whonix-legacy.preinst install || true

if [ -d "/var/lib/whonixcheck" ]; then
   ## Whonix 13: whonixcheck runs as user 'user'.
   ## Whonix 14: whonixcheck runs as user 'whonixcheck'.
   chown --recursive whonixcheck:whonixcheck "/var/lib/whonixcheck" || true
fi

## automate Tor permission fix
## https://www.whonix.org/wiki/Tor#Permissions_Fix
## https://forums.whonix.org/t/tor-error-your-tor-config-file-contains-at-least-one-error-var-lib-tor-tor-cannot-be-read-permission-denied/6200
## cat /var/lib/dpkg/info/tor.postinst | grep chown
## chown debian-tor:debian-tor /var/lib/tor
## chown debian-tor:adm /var/log/tor
if [ -d "/var/lib/tor" ]; then
   chown --recursive debian-tor:debian-tor /var/lib/tor || true
fi
if [ -d "/var/log/tor" ]; then
   chown --recursive debian-tor:adm /var/log/tor || true
fi

## sets: whonix_build_version
get_build_version

if command -v qubesdb-read >/dev/null 2>&1; then
   ## Qubes-Whonix

   ## Whonix 13 anon-base-files version: 3:2.0-1
   if dpkg --compare-versions "$whonix_build_version" lt "3:2.1-1" 2>/dev/null ; then
      whonix_repository_rerun
   fi
else
   ## Non-Qubes-Whonix

   if dpkg --compare-versions "$whonix_build_version" lt "12" 2>/dev/null ; then
      tb_folder_migration_whonix_eleven_to_twelve
   fi

   if dpkg --compare-versions "$whonix_build_version" lt "13" 2>/dev/null ; then
      timesync_apparmor_profile_delete
   fi

   if dpkg --compare-versions "$whonix_build_version" lt "14" 2>/dev/null ; then
      whonix_repository_rerun
   fi
fi

command_not_found_sources_list_fix

command_not_found_permission_fix
