#!/bin/bash

## Copyright (C) 2020 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e
set -o pipefail

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

if [ "$(id -u)" != "0" ]; then
   true "ERROR: Must run as root."
   true "sudo $0"
   exit 112
fi

export DEBDEBUG=1

## Sanity test. Do not continue with release upgrade if there are any dpkg issues.
dpkg --audit
dpkg --configure -a

## Standard "everyday" upgrade.
## https://www.whonix.org/wiki/Operating_System_Software_and_Updates
/usr/lib/security-misc/apt-get-update

## Sanity test.
apt-get-noninteractive --yes --no-install-recommends install nano

dpkg --audit
dpkg --configure -a

## Backports, testing, unstable should be disabled for release upgrade.
## Remove files which are mentioned in the wiki.
## https://www.whonix.org/wiki/Install_Software
rm -f /etc/apt/sources.list.d/backports.list
rm -f /etc/apt/sources.list.d/testing.list
rm -f /etc/apt/sources.list.d/unstable.list
rm -f /etc/apt/apt.conf.d/70defaultrelease

for file_name in /etc/apt/sources.list /etc/apt/sources.list.d/* ; do
   str_replace "buster" "bullseye" "$file_name"
done

repository-dist --enable --codename bullseye

## Get bullseye apt sources.
/usr/lib/security-misc/apt-get-update

## Release upgrade.
apt-get-noninteractive dist-upgrade --yes --no-install-recommends

dpkg --audit
dpkg --configure -a

service whonix-legacy restart

dpkg --audit
dpkg --configure -a

## Risky. User should review and do manually.
## https://www.whonix.org/wiki/Whonix_Debian_Packages#Re-install_Meta_Packages_and_Safely_Run_Autoremove
#apt-get-noninteractive --yes autoremove
#dpkg --audit
#dpkg --configure -a

## Currently not required.
#rm -f /var/cache/anon-base-files/first-boot-skel.done || true
#/usr/lib/helper-scripts/first-boot-skel || true

true "OK. Success."
